#!/system/xbin/sh
	cat /dev/input/event1 > /dev/keycheck&
	sleep 3
	kill -9 $!
	if [ -s /dev/keycheck -o -f /data/local/tmp/xrecovery ]
	then
	rm -f /data/local/tmp/xrecovery
	# remount rootfs rw
	mount -o remount,rw rootfs /

	# Umount MTDs
	umount -l /dev/block/mtdblock1
	umount -l /dev/block/mtdblock2
	umount -l /dev/block/mtdblock3

	# Mount recovery partition
	cd /
	rm -r /sbin
	rm -f etc
	if [ -f /system/bin/recovery.tar ]
	then
		tar -xf /system/bin/recovery.tar
	else
		tar -xf /system/bin/xrecovery.tar
	fi

	# Umount /system
	umount -l /dev/block/mtdblock0

	# chroot
	chroot / /init

	fi
	# Continue booting
	/system/bin/charger
	
	# remount rootfs rw
	mount -o remount,rw rootfs /
	chmod 0777 /dev -R
	chown 0.2000 /dev/oncrpc -R
	cd /
	rm init*
	rm logo.rle
	rm default.prop
	tar -xf /system/bin/ramdisk.tar
	# nobodyAtall - Fix 
	mkdir -p /minicm
	cd /minicm
	tar -xf /system/bin/ramdisk.tar
	sync
	# Umount /system, data and cache
	umount -l /dev/block/mtdblock0
	umount /dev/block/mtdblock3
	umount /dev/block/mtdblock1
	rmdir /system /data /cache /mnt
	# Mount /system to /minicm/system
	/sbin/mount_system
	sleep 1
	chroot /minicm /init
	
